// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/coffee.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CategoryFilter string                 `protobuf:"bytes,1,opt,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_api_proto_coffee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coffee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coffee_proto_rawDescGZIP(), []int{0}
}

func (x *MenuRequest) GetCategoryFilter() string {
	if x != nil {
		return x.CategoryFilter
	}
	return ""
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Tone          string                 `protobuf:"bytes,5,opt,name=tone,proto3" json:"tone,omitempty"`
	Img           string                 `protobuf:"bytes,6,opt,name=img,proto3" json:"img,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_api_proto_coffee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coffee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_api_proto_coffee_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *MenuItem) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *MenuItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_api_proto_coffee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coffee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coffee_proto_rawDescGZIP(), []int{2}
}

func (x *MenuResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_api_proto_coffee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coffee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coffee_proto_rawDescGZIP(), []int{3}
}

func (x *ProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProductResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Price           float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Tone            string                 `protobuf:"bytes,5,opt,name=tone,proto3" json:"tone,omitempty"`
	MainImg         string                 `protobuf:"bytes,6,opt,name=main_img,json=mainImg,proto3" json:"main_img,omitempty"`
	FullDescription string                 `protobuf:"bytes,7,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	ImageGallery    []string               `protobuf:"bytes,8,rep,name=image_gallery,json=imageGallery,proto3" json:"image_gallery,omitempty"`
	Characteristics map[string]string      `protobuf:"bytes,9,rep,name=characteristics,proto3" json:"characteristics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_api_proto_coffee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coffee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coffee_proto_rawDescGZIP(), []int{4}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *ProductResponse) GetMainImg() string {
	if x != nil {
		return x.MainImg
	}
	return ""
}

func (x *ProductResponse) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *ProductResponse) GetImageGallery() []string {
	if x != nil {
		return x.ImageGallery
	}
	return nil
}

func (x *ProductResponse) GetCharacteristics() map[string]string {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

var File_api_proto_coffee_proto protoreflect.FileDescriptor

const file_api_proto_coffee_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/coffee.proto\x12\acatalog\"6\n" +
	"\vMenuRequest\x12'\n" +
	"\x0fcategory_filter\x18\x01 \x01(\tR\x0ecategoryFilter\"\xa8\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x12\n" +
	"\x04tone\x18\x05 \x01(\tR\x04tone\x12\x10\n" +
	"\x03img\x18\x06 \x01(\tR\x03img\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\"7\n" +
	"\fMenuResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.catalog.MenuItemR\x05items\" \n" +
	"\x0eProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x03\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x12\n" +
	"\x04tone\x18\x05 \x01(\tR\x04tone\x12\x19\n" +
	"\bmain_img\x18\x06 \x01(\tR\amainImg\x12)\n" +
	"\x10full_description\x18\a \x01(\tR\x0ffullDescription\x12#\n" +
	"\rimage_gallery\x18\b \x03(\tR\fimageGallery\x12W\n" +
	"\x0fcharacteristics\x18\t \x03(\v2-.catalog.ProductResponse.CharacteristicsEntryR\x0fcharacteristics\x1aB\n" +
	"\x14CharacteristicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x90\x01\n" +
	"\x0eCatalogService\x126\n" +
	"\aGetMenu\x12\x14.catalog.MenuRequest\x1a\x15.catalog.MenuResponse\x12F\n" +
	"\x11GetProductDetails\x12\x17.catalog.ProductRequest\x1a\x18.catalog.ProductResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_api_proto_coffee_proto_rawDescOnce sync.Once
	file_api_proto_coffee_proto_rawDescData []byte
)

func file_api_proto_coffee_proto_rawDescGZIP() []byte {
	file_api_proto_coffee_proto_rawDescOnce.Do(func() {
		file_api_proto_coffee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_coffee_proto_rawDesc), len(file_api_proto_coffee_proto_rawDesc)))
	})
	return file_api_proto_coffee_proto_rawDescData
}

var file_api_proto_coffee_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_coffee_proto_goTypes = []any{
	(*MenuRequest)(nil),     // 0: catalog.MenuRequest
	(*MenuItem)(nil),        // 1: catalog.MenuItem
	(*MenuResponse)(nil),    // 2: catalog.MenuResponse
	(*ProductRequest)(nil),  // 3: catalog.ProductRequest
	(*ProductResponse)(nil), // 4: catalog.ProductResponse
	nil,                     // 5: catalog.ProductResponse.CharacteristicsEntry
}
var file_api_proto_coffee_proto_depIdxs = []int32{
	1, // 0: catalog.MenuResponse.items:type_name -> catalog.MenuItem
	5, // 1: catalog.ProductResponse.characteristics:type_name -> catalog.ProductResponse.CharacteristicsEntry
	0, // 2: catalog.CatalogService.GetMenu:input_type -> catalog.MenuRequest
	3, // 3: catalog.CatalogService.GetProductDetails:input_type -> catalog.ProductRequest
	2, // 4: catalog.CatalogService.GetMenu:output_type -> catalog.MenuResponse
	4, // 5: catalog.CatalogService.GetProductDetails:output_type -> catalog.ProductResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_coffee_proto_init() }
func file_api_proto_coffee_proto_init() {
	if File_api_proto_coffee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_coffee_proto_rawDesc), len(file_api_proto_coffee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_coffee_proto_goTypes,
		DependencyIndexes: file_api_proto_coffee_proto_depIdxs,
		MessageInfos:      file_api_proto_coffee_proto_msgTypes,
	}.Build()
	File_api_proto_coffee_proto = out.File
	file_api_proto_coffee_proto_goTypes = nil
	file_api_proto_coffee_proto_depIdxs = nil
}
