basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Backend API for managing coffee shop items, users, and roles.
  title: Coffee Shop API
  version: "1.0"
paths:
  /ping:
    get:
      description: Simple endpoint to check if server is alive
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping-Pong check
      tags:
      - test
swagger: "2.0"
